//! D2 acceptance criteria, exercised on the shielded-pool path:
//!   1. "a deposit with an invalid or out-of-range commitment must be
//!      rejected by contract logic"
//!   2. "valid arbitrary-amount deposits are accepted"
//!
//! Pool deposits go through `transact` (see lib.rs), which verifies a
//! join-split proof with in-circuit range proofs on the hidden note values
//! (`circuits/src/joinsplit.circom`, `Num2Bits(AMOUNT_BITS)` on every
//! `value`/`valueOut`, and on `publicDeposit`/`publicWithdraw`). These tests
//! run the REAL join-split proof (`joinsplit_fixture.rs`, generated by
//! `circuits/scripts/gen-joinsplit-vectors.mjs`'s "fixture" vector) through
//! the real verifier, not the `maybe_skip_verify` test bypass, so a rejected
//! claim is rejected by actual Groth16 verification rather than by a test
//! double standing in for it.
//!
//! Every assertion is on pool token balance and stored state (nullifiers),
//! not on the specific `Error` variant, per the repo testing rules (error
//! codes collide across contracts). The pool is minted well beyond any
//! amount a single fixture leg could move, so a blocked call is blocked by
//! verification, never by insufficient balance.
//!
//! This file is new and does not touch lib.rs, test.rs, or
//! groth16_fixture.rs, which another change has in flight. The two or three
//! helpers below are therefore copied from test.rs rather than shared with
//! it.

#![cfg(test)]

use soroban_sdk::testutils::Address as _;
use soroban_sdk::{token, Address, BytesN, Env, Vec};

use crate::joinsplit_fixture as jsx;
use crate::{ProofBytes, VkData, ZeekPay, ZeekPayClient};

// ---- copied from test.rs (fixture decoding helpers) ----

fn hex32(env: &Env, h: &str) -> BytesN<32> {
    let v = hex::decode(h).unwrap();
    let a: [u8; 32] = v.try_into().unwrap();
    BytesN::from_array(env, &a)
}
fn hex96(env: &Env, h: &str) -> BytesN<96> {
    let v = hex::decode(h).unwrap();
    let a: [u8; 96] = v.try_into().unwrap();
    BytesN::from_array(env, &a)
}
fn hex192(env: &Env, h: &str) -> BytesN<192> {
    let v = hex::decode(h).unwrap();
    let a: [u8; 192] = v.try_into().unwrap();
    BytesN::from_array(env, &a)
}

fn joinsplit_vkdata(env: &Env) -> VkData {
    let mut ic: Vec<BytesN<96>> = Vec::new(env);
    for h in jsx::IC {
        ic.push_back(hex96(env, h));
    }
    VkData {
        alpha1: hex96(env, jsx::ALPHA1),
        beta2: hex192(env, jsx::BETA2),
        gamma2: hex192(env, jsx::GAMMA2),
        delta2: hex192(env, jsx::DELTA2),
        ic,
    }
}

// ---- shared pool setup ----

/// Mint well beyond anything a single fixture deposit/withdraw leg could
/// move (deposit 7, withdraw 3 stroops), so a rejected `transact` proves the
/// guard fired, not that the pool ran dry.
const OVERFUND: i128 = 1_000_000_000;

struct Pool {
    env: Env,
    client: ZeekPayClient<'static>,
    id: Address,
    tok: token::Client<'static>,
    root: BytesN<32>,
    nulls: Vec<BytesN<32>>,
    cmts: Vec<BytesN<32>>,
    proof: ProofBytes,
    depositor: Address,
    recipient: Address,
}

/// A freshly initialised contract with the real pool VK set, the real
/// fixture's root posted, and both the depositor and the pool itself
/// over-funded. Verify bypass is deliberately left OFF everywhere in this
/// file: these tests exercise the real Groth16 verifier.
fn setup_pool() -> Pool {
    let env = Env::default();
    env.mock_all_auths();
    env.cost_estimate().budget().reset_unlimited();

    let admin = Address::generate(&env);
    let sac = env.register_stellar_asset_contract_v2(admin.clone());
    let id = env.register(ZeekPay, ());
    let client = ZeekPayClient::new(&env, &id);
    client.initialize(&admin, &sac.address());
    client.set_pool_vk(&joinsplit_vkdata(&env));

    let root = hex32(&env, jsx::PUBS[0]);
    client.post_root(&root);

    // jsx::PUBS = [root, nullifier0, nullifier1, outCommit0, outCommit1,
    // publicDeposit(7), publicWithdraw(3), tokenId(0)] — see
    // joinsplit_fixture.rs and the "fixture" vector in
    // circuits/scripts/gen-joinsplit-vectors.mjs.
    let mut nulls: Vec<BytesN<32>> = Vec::new(&env);
    nulls.push_back(hex32(&env, jsx::PUBS[1]));
    nulls.push_back(hex32(&env, jsx::PUBS[2]));
    let mut cmts: Vec<BytesN<32>> = Vec::new(&env);
    cmts.push_back(hex32(&env, jsx::PUBS[3]));
    cmts.push_back(hex32(&env, jsx::PUBS[4]));

    let proof = ProofBytes {
        a: hex96(&env, jsx::PROOF_A),
        b: hex192(&env, jsx::PROOF_B),
        c: hex96(&env, jsx::PROOF_C),
    };

    let depositor = Address::generate(&env);
    let recipient = Address::generate(&env);
    let sac_admin = token::StellarAssetClient::new(&env, &sac.address());
    let tok = token::Client::new(&env, &sac.address());
    sac_admin.mint(&depositor, &OVERFUND);
    sac_admin.mint(&id, &OVERFUND);

    Pool {
        env,
        client,
        id,
        tok,
        root,
        nulls,
        cmts,
        proof,
        depositor,
        recipient,
    }
}

// ---------------------------------------------------------------------------
// 1. Valid arbitrary-amount deposit is accepted.
// ---------------------------------------------------------------------------

/// The real fixture proof commits to publicDeposit = 7, publicWithdraw = 3
/// (chosen distinct and non-zero in the vector generator specifically so an
/// ordering bug would be detectable, not because 7 is special). The contract
/// enforces no particular amount: `derive_pool_public_inputs` binds whatever
/// `public_deposit` the caller passes into the verified statement, and the
/// circuit's `Num2Bits(64)` allows anything under 2^64. `7` here stands for
/// "any amount the prover actually proved" — `tampered_public_deposit_rejected`
/// below is the other half of that claim: an amount the prover did NOT prove
/// is rejected, so this acceptance is not a rubber stamp.
#[test]
fn valid_arbitrary_amount_deposit_accepted() {
    let p = setup_pool();
    let pool_before = p.tok.balance(&p.id);
    let depositor_before = p.tok.balance(&p.depositor);
    let recipient_before = p.tok.balance(&p.recipient);

    p.client.transact(
        &p.proof,
        &p.root,
        &p.nulls,
        &p.cmts,
        &7,
        &3,
        &0,
        &p.depositor,
        &p.recipient,
    );

    assert_eq!(
        p.tok.balance(&p.id),
        pool_before + 7 - 3,
        "pool balance must move by exactly public_deposit - public_withdraw"
    );
    assert_eq!(
        p.tok.balance(&p.depositor),
        depositor_before - 7,
        "depositor must be charged exactly public_deposit"
    );
    assert_eq!(
        p.tok.balance(&p.recipient),
        recipient_before + 3,
        "recipient must receive exactly public_withdraw"
    );
    assert!(p.client.is_nullifier_used(&p.nulls.get(0).unwrap()));
    assert!(p.client.is_nullifier_used(&p.nulls.get(1).unwrap()));
}

// ---------------------------------------------------------------------------
// 2. Tampered public_deposit (proof for X, claim X+1) is rejected.
// ---------------------------------------------------------------------------

/// Mutation check for this test: `valid_arbitrary_amount_deposit_accepted`
/// above is the "restore" half — same fixture, `public_deposit` fed back to
/// the honest value 7, and it passes. So the rejection below is not vacuous:
/// the same proof against the same root succeeds at 7 and fails at 8.
#[test]
fn tampered_public_deposit_rejected() {
    let p = setup_pool();
    let pool_before = p.tok.balance(&p.id);
    let depositor_before = p.tok.balance(&p.depositor);
    let recipient_before = p.tok.balance(&p.recipient);

    // Proof for public_deposit = 7; claim 8. derive_pool_public_inputs feeds
    // the CLAIMED amount into the verifier, so the verified statement no
    // longer matches what the proof attests to.
    let result = p.client.try_transact(
        &p.proof,
        &p.root,
        &p.nulls,
        &p.cmts,
        &8,
        &3,
        &0,
        &p.depositor,
        &p.recipient,
    );
    assert!(result.is_err(), "tampered public_deposit must be rejected");

    assert_eq!(
        p.tok.balance(&p.id),
        pool_before,
        "pool balance must be unchanged after a rejected transact"
    );
    assert_eq!(
        p.tok.balance(&p.depositor),
        depositor_before,
        "depositor must not be charged on a rejected transact"
    );
    assert_eq!(
        p.tok.balance(&p.recipient),
        recipient_before,
        "recipient must not be paid on a rejected transact"
    );
    assert!(
        !p.client.is_nullifier_used(&p.nulls.get(0).unwrap()),
        "nullifier must not be recorded on a rejected transact"
    );
    assert!(
        !p.client.is_nullifier_used(&p.nulls.get(1).unwrap()),
        "nullifier must not be recorded on a rejected transact"
    );
}

// ---------------------------------------------------------------------------
// 3. Out-of-range note value cannot produce a proof (circuit level), and the
//    contract-visible amount bound is enforced (contract level).
// ---------------------------------------------------------------------------

/// Circuit level (documented here, not re-run by `cargo test`): a hidden
/// note value at or above 2^64 cannot even produce a witness, let alone a
/// proof. `circuits/scripts/gen-joinsplit-vectors.mjs` generates and commits
/// `circuits/build/joinsplit_input_value_out_of_range.json`
/// (`valueOut[0] = 2^64`) with `expectAt: "Num2Bits:38"`: witness generation
/// for `JoinSplit(20, 64, 2, 2)` hits the `Num2Bits(64)` range check on that
/// output value and refuses to produce a witness. `node
/// circuits/scripts/gen-joinsplit-vectors.mjs` asserts this by name (its
/// harness fails the whole run if that vector fails at any other
/// constraint), so no proof — real or forged — can exist for an
/// out-of-range hidden note value. There is no equivalent test possible at
/// the contract layer for the hidden per-note values: they never reach the
/// contract in cleartext, only as Poseidon commitments/nullifiers, so the
/// contract has nothing to range-check directly.
///
/// Contract level: `public_deposit` and `public_withdraw` DO reach the
/// contract as plaintext amounts (they are the visible legs of the
/// join-split), and `transact` in lib.rs guards them directly with
/// `AMOUNT_MAX_EXCLUSIVE` before verification is even attempted. Exercise
/// that guard here with the real proof and an over-funded pool, so the
/// rejection is provably the range guard and not an empty pool.
#[test]
fn out_of_range_public_deposit_rejected() {
    let p = setup_pool();
    let pool_before = p.tok.balance(&p.id);
    let depositor_before = p.tok.balance(&p.depositor);

    let result = p.client.try_transact(
        &p.proof,
        &p.root,
        &p.nulls,
        &p.cmts,
        &crate::AMOUNT_MAX_EXCLUSIVE, // == 2^64, the guard's own boundary
        &3,
        &0,
        &p.depositor,
        &p.recipient,
    );
    assert!(
        result.is_err(),
        "public_deposit at AMOUNT_MAX_EXCLUSIVE must be rejected"
    );

    assert_eq!(
        p.tok.balance(&p.id),
        pool_before,
        "pool balance must be unchanged after a rejected transact"
    );
    assert_eq!(
        p.tok.balance(&p.depositor),
        depositor_before,
        "depositor must not be charged on a rejected transact"
    );
    assert!(!p.client.is_nullifier_used(&p.nulls.get(0).unwrap()));
    assert!(!p.client.is_nullifier_used(&p.nulls.get(1).unwrap()));
}

// ---------------------------------------------------------------------------
// 4. Wrong public-input count (nullifier shape) is rejected.
// ---------------------------------------------------------------------------

/// One test, two halves, same fixture data throughout: wrong shape first
/// (must be rejected, state unchanged), then the SAME call with the count
/// corrected back to `POOL_N_IN` (must now succeed). The second half is the
/// mutation check the task asks for: it proves the first assertion is live,
/// not a rejection that would have happened regardless of shape.
#[test]
fn wrong_nullifier_count_rejected_then_correct_count_accepted() {
    let p = setup_pool();
    let pool_before = p.tok.balance(&p.id);

    let mut one_null: Vec<BytesN<32>> = Vec::new(&p.env);
    one_null.push_back(p.nulls.get(0).unwrap());

    let result = p.client.try_transact(
        &p.proof,
        &p.root,
        &one_null, // one nullifier; POOL_N_IN == 2
        &p.cmts,
        &7,
        &3,
        &0,
        &p.depositor,
        &p.recipient,
    );
    assert!(result.is_err(), "wrong nullifier count must be rejected");
    assert_eq!(
        p.tok.balance(&p.id),
        pool_before,
        "pool balance must be unchanged after a rejected transact"
    );
    assert!(!p.client.is_nullifier_used(&p.nulls.get(0).unwrap()));

    // Mutation check: same proof, same root, same commitments — only the
    // nullifier count is fixed back to 2. If this failed too, the rejection
    // above would prove nothing about the shape check specifically.
    p.client.transact(
        &p.proof,
        &p.root,
        &p.nulls,
        &p.cmts,
        &7,
        &3,
        &0,
        &p.depositor,
        &p.recipient,
    );
    assert_eq!(
        p.tok.balance(&p.id),
        pool_before + 7 - 3,
        "correct-shape call must succeed and move the pool by deposit - withdraw"
    );
    assert!(p.client.is_nullifier_used(&p.nulls.get(0).unwrap()));
    assert!(p.client.is_nullifier_used(&p.nulls.get(1).unwrap()));
}
