// Deliverable 4 end-to-end validation: drives real arbitrary-amount
// deposit-to-claim cycles against the deployed testnet contract.
//
// This is the live app's own send and claim path, not a reimplementation. It
// imports lib/stealth, lib/commitment, lib/deposit, lib/prove_browser and
// lib/claim_tx unchanged, resolves handles through the deployed resolver, and
// fetches claim.wasm/claim.zkey from the deployed frontend. The only
// substitution is the signer: `signTx` is a local Stellar keypair instead of a
// Freighter popup, because a browser extension cannot be driven unattended.
//
// Run:
//   E2E_SENDER_SECRET=$(stellar keys show zeekpay-bench) \
//   npx tsx --env-file=../.env scripts/e2e_cycles.mts
//
// Results stream to scripts/e2e_results.json after every step, so a crash
// mid-run never loses a hash that is already on-chain.

import { readFileSync, writeFileSync } from "node:fs";
import * as StellarSdk from "@stellar/stellar-sdk";

const RESOLVER_URL = process.env.NEXT_PUBLIC_RESOLVER_URL!;
const ASSET_ORIGIN = process.env.E2E_ASSET_ORIGIN ?? "https://sendbullet.xyz";
const NETWORK_PASSPHRASE =
  process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE ?? StellarSdk.Networks.TESTNET;
const RPC_URL =
  process.env.NEXT_PUBLIC_SOROBAN_RPC_URL ?? "https://soroban-testnet.stellar.org";
const CONTRACT_ID = process.env.NEXT_PUBLIC_CONTRACT_ID!;
const OUT = new URL("./e2e_results.json", import.meta.url);

// prove_browser.ts fetches the circuit artifacts at site-relative paths, which
// have no base in Node. Resolve them against the deployed origin so the proofs
// are generated by the exact wasm and zkey sendbullet.xyz serves.
const realFetch = globalThis.fetch;
globalThis.fetch = ((input: string | URL | Request, init?: RequestInit) => {
  if (typeof input === "string" && input.startsWith("/")) {
    return realFetch(ASSET_ORIGIN + input, init);
  }
  return realFetch(input as never, init);
}) as typeof fetch;

const { deriveStealthDigest } = await import("../src/lib/stealth");
const { computeCommitment } = await import("../src/lib/commitment");
const { depositNote } = await import("../src/lib/deposit");
const { proveBrowser } = await import("../src/lib/prove_browser");
const { claimNote } = await import("../src/lib/claim_tx");

/** One cycle to run: who it is addressed to, and the arbitrary amount. */
interface CycleSpec {
  handle: string;
  /** Raw stroops. Deliberately not a round number: a visible round amount is
   *  the leak this deliverable closes. */
  amount: bigint;
  tokenId: number;
  /** Which funded payout wallet claims it, as an index into RECIPIENTS. */
  recipient: number;
}

interface CycleResult extends Omit<CycleSpec, "amount"> {
  n: number;
  amount: string;
  handleType?: string;
  recipientWallet?: string;
  commitment?: string;
  depositTx?: string;
  claimTx?: string;
  root?: string;
  nullifier?: string;
  amountCommitment?: string;
  leafWaitSeconds?: number;
  /** Claim credential. Kept out of the public evidence doc; see the comment at
   *  the assignment site. */
  secret?: string;
  recipientDigest?: string;
  error?: string;
}

const CYCLES: CycleSpec[] = [
  { handle: "github:mdla03", amount: 31_415_927n, tokenId: 1, recipient: 0 },
  { handle: "github:vkenjo", amount: 27_182_818n, tokenId: 1, recipient: 1 },
  { handle: "github:lancecolorina", amount: 16_180_339n, tokenId: 1, recipient: 2 },
  { handle: "github:gohaty", amount: 141_421_356n, tokenId: 1, recipient: 0 },
  { handle: "github:jairuss0", amount: 57_721_566n, tokenId: 1, recipient: 1 },
  { handle: "github:jimsondavid", amount: 23_606_797n, tokenId: 1, recipient: 2 },
];

function keypairFromEnv(name: string): StellarSdk.Keypair {
  const secret = process.env[name];
  if (!secret) throw new Error(`${name} is required`);
  return StellarSdk.Keypair.fromSecret(secret);
}

const SENDER = keypairFromEnv("E2E_SENDER_SECRET");
const RECIPIENTS = [
  keypairFromEnv("E2E_RECIP_1_SECRET"),
  keypairFromEnv("E2E_RECIP_2_SECRET"),
  keypairFromEnv("E2E_RECIP_3_SECRET"),
];

/** Stands in for Freighter: signs the prepared XDR with a local keypair. */
function localSigner(kp: StellarSdk.Keypair) {
  return async (xdr: string): Promise<string> => {
    const tx = StellarSdk.TransactionBuilder.fromXDR(xdr, NETWORK_PASSPHRASE);
    tx.sign(kp);
    return tx.toXDR();
  };
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

interface Resolved {
  stellarAddress: string;
  zeekPayPubKey: string;
  type?: string;
}

async function resolveHandle(handle: string): Promise<Resolved> {
  const res = await realFetch(
    `${RESOLVER_URL}/resolve?q=${encodeURIComponent(handle)}`
  );
  const body = (await res.json()) as Resolved & { found?: boolean };
  if (!res.ok || !body.found) {
    throw new Error(`resolve ${handle} failed: HTTP ${res.status}`);
  }
  if (!body.zeekPayPubKey) {
    throw new Error(`resolve ${handle} returned no published key`);
  }
  return body;
}

/** Block until the deployed indexer has inserted the deposit's leaf and the
 *  tree can produce a path for it. Until that happens there is nothing to
 *  prove membership against. */
async function waitForLeaf(commitment: string, timeoutMs = 10 * 60_000): Promise<number> {
  const started = Date.now();
  for (;;) {
    const res = await realFetch(
      `${RESOLVER_URL}/path?commitment=${encodeURIComponent(commitment)}`
    );
    if (res.ok) return Math.round((Date.now() - started) / 1000);
    if (res.status !== 404) {
      throw new Error(`/path returned HTTP ${res.status}`);
    }
    if (Date.now() - started > timeoutMs) {
      throw new Error(`leaf for ${commitment} never indexed`);
    }
    await sleep(10_000);
  }
}

/** Whether the contract already knows a root, by simulation (no fee, no
 *  signature). The indexer inserts a leaf and posts the resulting root as two
 *  separate steps, so `/path` hands out a root that is briefly not yet
 *  on-chain. Claiming in that window fails with UnknownRoot (error #5), and
 *  retrying the same proof does not help: by then the indexer may have moved
 *  on to a newer root and the one the proof commits to never gets posted. The
 *  only reliable order is to prove, check, and re-prove against whatever the
 *  tree says once the previous root has landed. */
async function isKnownRoot(rootHex: string): Promise<boolean> {
  const rpc = new StellarSdk.rpc.Server(RPC_URL);
  const contract = new StellarSdk.Contract(CONTRACT_ID);
  const op = contract.call(
    "is_known_root",
    StellarSdk.xdr.ScVal.scvBytes(Buffer.from(rootHex, "hex"))
  );
  const account = await rpc.getAccount(SENDER.publicKey());
  const tx = new StellarSdk.TransactionBuilder(account, {
    fee: "100",
    networkPassphrase: NETWORK_PASSPHRASE,
  })
    .addOperation(op)
    .setTimeout(30)
    .build();
  const sim = await rpc.simulateTransaction(tx);
  if (!StellarSdk.rpc.Api.isSimulationSuccess(sim) || !sim.result) {
    throw new Error(`is_known_root simulation failed: ${JSON.stringify(sim)}`);
  }
  return StellarSdk.scValToNative(sim.result.retval) === true;
}

type Proof = Awaited<ReturnType<typeof proveBrowser>>;

/** Prove against the current tree, and only return once the root that proof
 *  commits to is one the contract will accept. */
async function proveAgainstKnownRoot(
  args: Parameters<typeof proveBrowser>,
  attempts = 12
): Promise<Proof> {
  for (let i = 0; i < attempts; i++) {
    const proof = await proveBrowser(...args);
    if (await isKnownRoot(proof.root)) return proof;
    console.log(
      `    root ${proof.root.slice(0, 12)}… not posted yet, re-proving in 20s (${i + 1}/${attempts})`
    );
    await sleep(20_000);
  }
  throw new Error("the indexer never posted a root this note could prove against");
}

/** Everything after the deposit has confirmed: wait for the leaf, prove
 *  against a posted root, and claim. Split out from the deposit so a run
 *  interrupted between the two (a dropped request, a killed process) can be
 *  finished later from the persisted secret instead of stranding the note. */
async function settle(row: CycleResult): Promise<void> {
  if (!row.secret || !row.recipientDigest || !row.commitment) {
    throw new Error(`cycle ${row.n} has no claim credential to settle with`);
  }
  console.log("    waiting for the indexer to insert the leaf…");
  row.leafWaitSeconds = await waitForLeaf(row.commitment);
  console.log(`    leaf indexed after ${row.leafWaitSeconds}s`);

  console.log("    proving…");
  const proof = await proveAgainstKnownRoot([
    row.secret,
    row.recipientDigest,
    row.amount,
    String(row.tokenId),
  ]);
  row.root = proof.root;
  row.nullifier = proof.nullifier;
  row.amountCommitment = proof.amountCommitmentX + proof.amountCommitmentY;
  flush();

  const payout = RECIPIENTS[row.recipient];
  row.recipientWallet = payout.publicKey();
  console.log(`    claiming into ${payout.publicKey()}…`);
  row.claimTx = await claimNote(
    payout.publicKey(),
    proof.proof_a,
    proof.proof_b,
    proof.proof_c,
    proof.root,
    proof.nullifier,
    // The contract takes the digest as 32-byte big-endian hex; stealth
    // derivation and the prover both work in decimal (ClaimView does the same
    // conversion at the same boundary).
    BigInt(row.recipientDigest).toString(16).padStart(64, "0"),
    BigInt(row.amount),
    localSigner(payout),
    row.tokenId,
    proof.amountCommitmentX,
    proof.amountCommitmentY
  );
  console.log(`    claim    ${row.claimTx}\n`);
}

const results: CycleResult[] = [];
const flush = () => writeFileSync(OUT, JSON.stringify(results, null, 2) + "\n");

console.log(`sender    ${SENDER.publicKey()}`);
console.log(`recipients ${RECIPIENTS.map((r) => r.publicKey()).join(" ")}`);
console.log(`contract  ${process.env.NEXT_PUBLIC_CONTRACT_ID}`);
console.log(`assets    ${ASSET_ORIGIN}/circuits/claim.{wasm,zkey}\n`);

// E2E_SKIP/E2E_LIMIT select a window of the list, so the harness can be proven
// out on one cycle before committing the rest, and a partial run resumed
// without re-depositing what already landed.
const SKIP = Number(process.env.E2E_SKIP ?? 0);
const PLAN = CYCLES.slice(SKIP, SKIP + Number(process.env.E2E_LIMIT ?? CYCLES.length));

// E2E_RESUME finishes deposits that already landed instead of making new ones:
// it reads the previous run's file and settles every row that has a deposit but
// no claim. Nothing new is deposited in this mode.
if (process.env.E2E_RESUME === "1") {
  const prior = JSON.parse(readFileSync(OUT, "utf8")) as CycleResult[];
  results.push(...prior);
  const pending = prior.filter((r) => r.depositTx && !r.claimTx);
  console.log(`resuming ${pending.length} unclaimed deposit(s)\n`);
  for (const row of pending) {
    console.log(`[${row.n}] ${row.handle}  ${row.amount} stroops (resume)`);
    delete row.error;
    try {
      await settle(row);
    } catch (e) {
      row.error = e instanceof Error ? e.message : String(e);
      console.error(`    FAILED: ${row.error}\n`);
    }
    flush();
  }
  const settled = prior.filter((r) => r.claimTx).length;
  console.log(`${settled}/${prior.length} cycles now complete.`);
  process.exit(settled === prior.length ? 0 : 1);
}

for (const [i, spec] of PLAN.entries()) {
  const row: CycleResult = { n: SKIP + i + 1, ...spec, amount: spec.amount.toString() };
  results.push(row);
  console.log(`[${row.n}/${CYCLES.length}] ${spec.handle}  ${spec.amount} stroops`);

  try {
    const resolved = await resolveHandle(spec.handle);
    row.handleType = resolved.type;

    // Per-payment stealth digest, exactly as SendForm does it: a fresh
    // ephemeral X25519 key per payment, so two payments to one handle share
    // no on-chain value.
    const { recipientDigest } = deriveStealthDigest(resolved.zeekPayPubKey);

    const secretBytes = new Uint8Array(32);
    crypto.getRandomValues(secretBytes);
    secretBytes[0] = 0; // keep the secret below the BLS12-381 field order
    const secret = BigInt(
      "0x" + Buffer.from(secretBytes).toString("hex")
    ).toString();

    const commitment = computeCommitment(
      secret,
      recipientDigest,
      spec.amount.toString(),
      String(spec.tokenId)
    );
    row.commitment = commitment;
    // Persisted before the deposit, not after: these two values are the whole
    // claim credential, and without them a deposit that lands but fails to
    // claim leaves its note unspendable forever. e2e_results.json is
    // gitignored for exactly this reason; the evidence doc carries hashes only.
    row.secret = secret;
    row.recipientDigest = recipientDigest;
    flush();

    console.log("    depositing…");
    row.depositTx = await depositNote(
      SENDER.publicKey(),
      BigInt(commitment),
      spec.amount,
      localSigner(SENDER),
      spec.tokenId
    );
    console.log(`    deposit  ${row.depositTx}`);
    flush();

    await settle(row);
  } catch (e) {
    row.error = e instanceof Error ? e.message : String(e);
    console.error(`    FAILED: ${row.error}\n`);
  }
  flush();
}

const done = results.filter((r) => r.depositTx && r.claimTx).length;
console.log(`${done}/${PLAN.length} cycles completed in this run. Results in ${OUT.pathname}`);
if (done < PLAN.length) process.exitCode = 1;

// The Soroban RPC client keeps sockets alive, which holds the event loop open
// long after the last cycle is done. Every result is already flushed.
process.exit(process.exitCode ?? 0);
